### ISSUE TITLE
编译分包错误

### ISSUE THREAD

**Issue by jacksuc** [gudqs7/wxappUnpacker#10]
D:\Program Files\wxappUnpacker-gudqs7\wuLib.js:115
            if (err) throw Error("Scan dir error: " + err);
                     ^
Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'D:\Program File
s\wxappUnpacker-gudqs7\gly\app-service.js'

D:\......是正确的。怎么会报错。

下面是源包~！
[gly.zip](https://github.com/gudqs7/wxappUnpacker/files/3195456/gly.zip)

**Comment by rocky-76** [comment]
我也出现了这个错误  你解决了吗

**Comment by jacksuc** [comment]
> 我也出现了这个错误 你解决了吗

没有，不知道是写法有问题还是哪里的问题...
