### ISSUE TITLE
你好老哥，提取不了图片

### ISSUE THREAD

**Issue by jeason1997** [gudqs7/wxappUnpacker#2]
@gudqs7 刚研究了下，不是反编译器的问题，是因为小游戏，图片资源太多，他们都不放在程序里，都是动态联网加载的，所以解包解不了。

**Comment by vzhuaner0321** [comment]
大神、给你反馈一写错误、基本上很多包解出来的wxml是不完整的、很多报错

**Comment by gudqs7** [comment]
> 大神、给你反馈一写错误、基本上很多包解出来的wxml是不完整的、很多报错

@vzhuaner0321  最新版可能解决了这个问题

**Comment by gudqs7** [comment]
@jeason1997 
小游戏没怎么管, 估计也是分包问题

**Comment by gudqs7** [comment]
@jeason1997  ok
