### ISSUE TITLE
解压子包的时候报错

### ISSUE THREAD

**Issue by rocky-76** [gudqs7/wxappUnpacker#8]
![54A5FFAE-1A5A-4421-966C-29F44AA79EB9](https://user-images.githubusercontent.com/9004674/58184961-b3a78a00-7ce4-11e9-8c41-67ea6bc95e99.png)
例如 a 为主包 ，b为子包， 解完主包得到文件夹a 然后解子包输入命令                                                
` node wuWxapkg.js /user/xx/b.wxapkg -s=/user/xx/a `  就会报上面的错误提示

**Comment by Surile** [comment]
@gudqs7

**Comment by Surile** [comment]
![image](https://user-images.githubusercontent.com/28652894/58236226-03ce2d00-7d75-11e9-81bc-3393d84833ec.png)

![image](https://user-images.githubusercontent.com/28652894/58236265-1b0d1a80-7d75-11e9-8ae3-11bfd4b7d286.png)

**Comment by gudqs7** [comment]
@Surile  @rocky-76  看下命令, 自己检查 -s= 后面的路径是否存在

**Comment by Surile** [comment]
@gudqs7 路径是存在的。第二张图就是路径。在testpkg/yumi是主包小程序。

**Comment by wangxianglong** [comment]
> @gudqs7 路径是存在的。第二张图就是路径。在testpkg/yumi是主包小程序。

我也遇到这个问题，请问解决了吗？
