### ISSUE TITLE
子包解包后wxss文件无样式内容

### ISSUE THREAD

**Issue by qq239574** [gudqs7/wxappUnpacker#9]
大神，用你的工具能解包；补全文件wxss，但是子包解包后的wxss里无样式内容！

**Comment by gudqs7** [comment]
不会吧

**Comment by qq239574** [comment]
确实是的，子包解包，wxss是工具自动补全的文件，不是解子包的文件wxss

**Comment by gudqs7** [comment]
@qq239574  解压子包时候 -s 指定主包路径文件夹, 指定的啥, wxss 就在哪

**Comment by qq239574** [comment]
解包-s正常，wxss文件是有的，只是wxss里并没有样式内容。例如：
detail/detail.wxss
解包后 /* detail/detail.wxss */
wxss内容只是路径而已，没有具体样式内容
